### ISSUE TITLE
Several tests disabled, to be enabled again after fix

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/mechanical_turk#100]
Some mechanical turk tests fail. Issues have been opened for this.

These tests are temporarily set to "pending" by using `xit`.
They have to be enabled again as the issues are closed.

### General
- [x]  Changing the origin of LNG and natural gas does not affect dashboard values 
_regasified LNG importing all LNG from Qatar should increase CO2 emissions_
 ./spec/demand/lng_spec.rb:32
https://github.com/quintel/etmodel/issues/2485
- [x] Excess electricity usage is lower than the total excess electricity
_Flexibility elextricity Conservatoin Electricity should be conserved betwee excess production and storage_
./spec/flexibility/flexibility_spec.rb:347
https://github.com/quintel/etmodel/issues/2478
- [x] Connection between households_useful_demand_for_hot_water_for_houses_with_p2h and households_flexibility_p2h_electricity seems broken
_Flexibility P2H In a scenario increasing the number of P2H units should decrease CO2 emissions_
./spec/flexibility/flexibility_spec.rb:126
https://github.com/quintel/etmodel/issues/2477
### Network related
- [ ] Network costs drop too much due to insulation
_ETFlex Scoring mechanism Demand Insulation level to R = 3.0 should lower your cost score_
./spec/etflex/score_spec.rb:67
- [x] With default settings additional investment costs are non-zero on beta
_Network costs In a start scenario no infrastructure investments should be needed_
./spec/network?network_infrastructure_investements_spec.rb:11
https://github.com/quintel/etmodel/issues/2481

notifying @ChaelKruip and @antw

**Comment by ChaelKruip** [comment]
https://github.com/quintel/etmodel/issues/2478 has been closed

**Comment by ChaelKruip** [comment]
- [ ] rspec ./spec/flexibility/flexibility_spec.rb:255 # Flexibility P2H for industry In a scenario with excess electricity increasing the number of P2H units in the paper sector should decrease the electricity curtailed
- [ ] rspec ./spec/flexibility/flexibility_spec.rb:264 # Flexibility P2H for industry In a scenario with excess electricity increasing the number of P2H units in the paper sector should decrease the electricity exported
- [ ] rspec ./spec/flexibility/flexibility_spec.rb:273 # Flexibility P2H for industry In a scenario with excess electricity increasing the number of P2H units in the paper sector should decrease CO2 emissions
- [ ] rspec ./spec/flexibility/flexibility_spec.rb:283 # Flexibility P2H for industry In a scenario with excess electricity increasing the number of P2H units in the paper sector should decrease the gas use of that sector
- [ ] rspec ./spec/flexibility/flexibility_spec.rb:379 # Flexibility Demand response heat pumps, buffer size In a scenario with deficits and 100 should decrease the deficits
- [ ] rspec ./spec/demand/hybrid_heatpump_spec.rb:14 # Hybrid heat pump Hybrid heat pummp general Removing all residences should give the initial input shares
- [ ] rspec ./spec/demand/hybrid_heatpump_spec.rb:46 # Hybrid heat pump Hybrid heat pummp general Resetting sliders to their initial conditions should return the initial shares
- [ ] rspec ./spec/demand/hybrid_heatpump_spec.rb:74 # Hybrid heat pump Hybrid heat pummp general Setting the four relevant HHP sliders should change the shares of gas, electricity and ambient_heat by the correct amount
- [ ] rspec ./spec/demand/hybrid_heatpump_spec.rb:167 # Hybrid heat pump Hybrid heat gas usage Changing to space heating profile 1987 should result in more gas use by HHP's
