### ISSUE TITLE
outdated tests for hybrid heat pumps

### ISSUE THREAD

**Issue by MartLubben** [quintel/mechanical_turk#105]
Hi Dorine,

The Mechanical Turk has some issues due to the hybrid pump. At this moment the pumps are dynamic. However the turk (~/mechanical_turk/spec/demand/hybrid_heatpump_spec.rb) is set up for the static calculations.

Questions:
1. Can these test be removed?
2 Do we need new tests?

----------------
Failures:
  1) Hybrid heat pump Hybrid heat pump general Removing all residences should give the initial input shares
     Failure/Error: expect(@scenario.turk_hhp_network_gas_input_share.increase).to be == 0.0
       expected: == 0.0
            got:    0.08333576918760117
     # ./demand/hybrid_heatpump_spec.rb:20:in `block (4 levels) in <top (required)>'

  2) Hybrid heat pump Hybrid heat pummp general Resetting sliders to their initial conditions should return the initial shares
     Failure/Error: expect(@scenario.turk_hhp_network_gas_input_share.increase).to be == 0.0

  3) Hybrid heat pump Hybrid heat pummp general Setting the four relevant HHP sliders should change the shares of gas, electricity and ambient_heat by the correct amount
     Failure/Error: expect(@scenario.turk_hhp_network_gas_input_share.increase).to be == - 0.14058106841612025
       expected: == -0.14058106841612025
            got:    -0.10410565536722584
     # ./demand/hybrid_heatpump_spec.rb:84:in `block (4 levels) in <top (required)>'

**Comment by ChaelKruip** [comment]
@MartLubben can you reference a pull request that closes this? Or can you explain why this is not relevant anymore?

**Comment by ChaelKruip** [comment]
Fixed with https://github.com/quintel/mechanical_turk/pull/112

**Comment by MartLubben** [comment]
@ Chael yes: https://github.com/quintel/mechanical_turk/pull/112

The merit order caused already changes in the hhp_network_gas_input_share between 2015 and 2050. Even though the sliders of residences did not change it.

**Comment by ChaelKruip** [comment]
> The merit order caused already changes in the hhp_network_gas_input_share between 2015 and 2050. Even though the sliders of residences did not change it.

I know, but was this intended? Is that behaviour that we expect? Did this test start failing when Fever was first introduced? Or did it work at first or broke because of a later change?
