### ISSUE TITLE
The test for Cold Snap fails

### ISSUE THREAD

**Issue by MartLubben** [quintel/mechanical_turk#106]
Hi Dorine,

The test for cold snap fails due to the fact that the curve changes, but not the total heat demand. A solution could be to automatically set de climate in the test to -2. This will increase total heat demand. 

~/mechanical_turk/spec/demand/hybrid_heatpump_spec.rb   

Issue: 
4) Hybrid heat pump Hybrid heat gas usage Changing to space heating profile 1987 should result in more gas use by HHP's
     Failure/Error: expect(@scenario.turk_hhp_network_gas_input_share).to increase
       expected an increase, but actually got a decrease of 0.006870188536111682
     # ./demand/hybrid_heatpump_spec.rb:170:in `block (4 levels) in <top (required)>'

**Comment by DorinevanderVlies** [comment]
I would expect the gas use to increase even when the average temperature does not change. As the cold snap profile has more peaks the relative need of the gas part of HHP's is higher than for a flat profile. I'll look into this
