### ISSUE TITLE
Fix spec for chemical industry

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/mechanical_turk#126]
./spec/industry_chemical/chemical_industry_spec.rb:50 # Standard scenario: Chemical industry Heating: Using coal-fired heaters instead of gas-fired in refineries should increase demand and CO2 emission, but decrease cost and bio-footprint

**Comment by redekok** [comment]
I've created an issue (https://github.com/quintel/etmodel/issues/2978) for ETModel. Let's check if fixing this issue for ETModel also fixes this mechanical turk issue.

**Comment by redekok** [comment]
> I've created an issue ([quintel/etmodel#2978](https://github.com/quintel/etmodel/issues/2978)) for ETModel. Let's check if fixing this issue for ETModel also fixes this mechanical turk issue.

It does! So closing this issue.
