### ISSUE TITLE
Add a spec to check whether all relevant nodes are included the application group

### ISSUE THREAD

**Issue by redekok** [quintel/mechanical_turk#142]
It might be a good idea to add a spec that checks whether `SUM(V(G(application_group),final_demand))` results in the same output value as `SUM(V(G(final_demand_group),demand))`.

Related to https://github.com/quintel/etmodel/issues/3260

**Comment by michieldenhaan** [comment]
Closing, superseded by: https://github.com/quintel/mechanical_turk/issues/150
