### ISSUE TITLE
Hybrid heat pump specs needed

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/mechanical_turk#79]
We need to test (automatically) if the following things work:

- [x] The shares of gas, electricity and ambient heat change by the correct amount for the four relevant sliders
- [x] Resetting sliders to their initial conditions results in the initial shares
- [x] The COP remains constant 
- [x] Nothing weird happens when all houses are removed

**Comment by jorisberkhout** [comment]
Adding February deploy milestone.
