### ISSUE TITLE
Network mech_test fails for industry gas CHP

### ISSUE THREAD

**Issue by RobTerwel** [quintel/mechanical_turk#83]
This <a href="https://github.com/quintel/mechanical_turk/blob/master/spec/network/network_infrastructure_investments_spec.rb#L109-L115"a>network infrastructure test for industry CHPs<a/> fails because the CHP which is tested is connected to the **MV** grid in the graph but appears in this **HV** grid  <a href="https://github.com/quintel/etsource/blob/master/gqueries/modules/network/converter_groups/high_voltage_electricity_production.gql#L29"a>query<a/>.  

If this `industry_chp_combined_cycle_gas_power_fuelmix` indeed belongs in this gquery, we could replace it with a different, 'fully MV' industry CHP like `industry_chp_ultra_supercritical_coal`. If it doesn't belong there, it will be removed in https://github.com/quintel/etsource/issues/1052

**Comment by jorisberkhout** [comment]
As discussed in https://github.com/quintel/etsource/issues/1052, the `industry_chp_combined_cycle_gas_power_fuelmix` should indeed be connected to the HV-net.

> If this `industry_chp_combined_cycle_gas_power_fuelmix` indeed belongs in this gquery, we could replace it with a different, 'fully MV' industry CHP like `industry_chp_ultra_supercritical_coal`.

@RobTerwel , I like this solution. Could you implement this?

**Comment by RobTerwel** [comment]
> Could you implement this?

I will!
