### ISSUE TITLE
Adjust mechanical turk specs to the new carrier prices

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/mechanical_turk#91]
The carrier prices were updated by the commits in https://github.com/quintel/etsource/pull/1080. Obviously many costs specs now fails. Would you be so kind to adjust the mechanical turk specs to the new carrier prices, @RobTerwel ?

**Comment by ChaelKruip** [comment]
@RobTerwel please note that I have made [a script](https://github.com/quintel/mechanical_turk/tree/master/scripts/query_generator/cost_update) to do this with.

That might save you a lot of time :smile:

**Comment by RobTerwel** [comment]
> @RobTerwel please note that I have made a script to do this with.

> That might save you a lot of time :smile:

Great contender for best usefulness : length-of-message ratio of the week - thanks @ChaelKruip !
