### ISSUE TITLE
LNG from Qatar spec fails

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/mechanical_turk#96]
Since this commit the CO2 does not change when setting LNG from Qatar to 100%: https://github.com/quintel/mechanical_turk/commit/ca5ca1f8b2f4747fca7464066032ad714020cb27

I don't understand why this happens as the CO2 values from Qatar-lng seem to be the highest. Is Qatar already the default perhaps?

Assigning @jorisberkhout as he is the author of the commit that seems to have broken this.

**Comment by ChaelKruip** [comment]
@jorisberkhout can you have a look at this? Is the FCE calculation broken?

**Comment by redekok** [comment]
The Qatar-LNG spec seemed to be working fine again after enabling it. Will be resolved by https://github.com/quintel/mechanical_turk/pull/130 so closing this issue.
